---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true

- name: Upgrade all packages on servers
  apt: upgrade=dist force_apt_get=yes
  become: true
  
- name: Install python pip
  apt:
    pkg:
      - python3-dev
      - python3-pip
      - libxml2
      - libxml2-dev
      - libxslt1-dev
      - lib32z1-dev
      - libssl-dev
      - zlib1g-dev
  connection: local
  become: true

- name: Install Python Libs
  #debugger: always
  apt:
    pkg:
      - libxml2
      - libxml2-dev
      - libxslt1-dev
      - lib32z1-dev
      - libssl-dev
      - zlib1g-dev
  connection: local
  become: true

- name: Install fucking lxml
  command: "pip3 install lxml"
  environment:
    CFLAGS: "-O0"
  connection: local
  become: true

- name: Download app from Artifactory
  maven_artifact:
    group_id: pl.jp
    artifact_id: jpapp
    repository_url: "{{ repository_url }}"
    username: "{{ username }}"
    password: "{{ password }}"
    dest: "{{ artifact_name }}"
  connection: local
