---
- include_tasks: install_libs.yml

- name: Install (JRE)
  apt:
    name: default-jre
    update_cache: yes
  become: true

- name: Copyt of jp app
  copy:
    src: "{{ artifact_name }}"
    dest: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  notify:
  - Start apki

- name: Create app service on ec2
  copy:
    src: application.service
    dest:  /etc/systemd/system/
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  become: yes

#- name: Uruchomienie aplikacji
#  service:
#    name: application
#    state: restarted
#  become: true
