---
- name: Instalacja lxml + inne
  become: true
  apt:
    pkg:
      - python3-dev
      - libxml2
      - libxml2-dev
      - libxslt1-dev
      - lib32z1-dev
      - libssl-dev
      - zlib1g-dev
      - python3-pip
  connection: local
- name: install lxml
  command: "pip install lxml"
  environment:
    CFLAGS: "-O0"
  connection: local

- name: Pobranie apki z artifactory
  maven_artifact:
    group_id: pl.jp
    artifact_id: jp
    repository_url: "{{ repository_url }}"
    username: "{{ username }}"
    password: "{{ password }}"
    dest: "{{ artifact_name }}"
  connection: local
